# Change the ARDUINO_DIR path to point to your arduino IDE source files.
ARDUINO_DIR = /home/zuhraa470/arduino-1.8.4
BOARD_TAG = ethernet
ARDUINO_SKETCHBOOK = ../../arduino-mk
ARDMK_DIR = ../../arduino-mk
AVR_TOOLS_DIR=/usr
ARDUINO_LIBS = Wire SPI EEPROM Adafruit_HTU21DF_Library Adafruit_MCP9808_Library SparkFun_SX1509_Arduino_Library Ethernet Adafruit_SleepyDog
include ../Arduino.mk
